### ISSUE TITLE
Keefile path is lost

### ISSUE THREAD

**Issue by ChadSchelfhoutAvalara** [JanisEst/KeePassQuickUnlock#27]
I like the concept of using the QuickUnlock, but if a keyfile is used along with the Master Password then the path is lost and not shown in the keyfile drop down.   Is there an easy way to switch back to the original path if the Master Password is required?

**Comment by JanisEst** [comment]
Short answer: no.

See #19, #18 or #13 for more informations.
Looks like I need to add this info to the readme too.
