### ISSUE TITLE
QuickUnlock window does not open after beeing locked out after inactivity

### ISSUE THREAD

**Issue by DerLude** [JanisEst/KeePassQuickUnlock#30]
Hi Janis!
I noticed a strange behaviour of QuickUnlock. It works fine if I use the "QuickUnlock" entry in my database, however, with the "Part of Master Password" I noticed a strange behaviour. I set this up similar to keepass2android to use the last 3 characters of my master password. If I lock the database manually, the QuickUnlock window appears and quick-unlocking works as expected. However, if the database is locked after several seconds of inactivity (set up under Security options), the QuickUnlock window does not appear and I need to enter my full password and file in the usual keepass unlock window. Is there any difference between unlocking manually and unlocking automatically after x seconds?

Cheers

PS: I use KeePass 2.38 with QuickUnlock 2.4.0.0 under Ubuntu 14.04.

**Comment by JanisEst** [comment]
I don't think the problem is the auto-lock after some seconds. Should be this by-design problem: https://github.com/JanisEst/KeePassQuickUnlock#how-to-use
