### ISSUE TITLE
Not compatible with KeePass2, V 2.43

### ISSUE THREAD

**Issue by ChEh-git** [JanisEst/KeePassQuickUnlock#36]
Does not work with Keepass2, V2.43 on Win 10.
- Plugin in Program-folder of Keepass2 (subfolder "plugins"
- Key-Entry "QuickUnlock" in Database
- QuickUnlock tab exists in "Options"-Menu
- But QuickUnlock Window ist not opening when starting Keepass2 with according Database

**Comment by JanisEst** [comment]
QuickUnlock only works for one KeePass "session". If you exit the KeePass application and restart, it will not work. The shorter QuickUnlock key is kept encrypted in KeePass memory which gets erased when KeePass gets closed.

**Comment by ChEh-git** [comment]
Thx for the quick reply.
I got it now, and it works as you describe it.
Regards
Chris


Am Mi., 25. Sept. 2019 um 19:18 Uhr schrieb Janis Estelmann <
notifications@github.com>:
