### ISSUE TITLE
No more QuickUnlock prompt after locking database twice

### ISSUE THREAD

**Issue by thomaspdt** [JanisEst/KeePassQuickUnlock#41]
Version: Windows 10, KeePass 2.47 (64-bit)

## Expected behavior

1. Open database for the first time with master password
2. Lock the database
3. Open database. QuickUnlock prompt appears.
4. Lock the database
5. Open database. QuickUnlock prompt appears.
6. and so on...

## Current behavior

1. Open database for the first time with master password
2. Lock the database
3. Open database. QuickUnlock prompt appears.
4. Lock the database
5. Open database. QuickUnlock prompt **does not appear**. Instead, user is asked to enter master password.
6. Lock database.
7. Open database. QuickUnlock prompt appears again.
8. And so on...

## How to reproduce?

The bug occurs when the PartOf mode is selected. QuickUnlock works fine if Custom Entry mode only is selected.

**Comment by loeffelpan** [comment]
Same here.
Worked around it with an QuickUnlock entry containing part of my master password.

Any help?

**Comment by thomaspdt** [comment]
#34 Same issue already created.

**Comment by JanisEst** [comment]
That's the intended behaviour. See the gray part [here](https://github.com/JanisEst/KeePassQuickUnlock/blob/master/README.md#how-to-use). There is nothing I can do about it.

**Comment by loeffelpan** [comment]
Ah, now I got it.
Sorry for missing that in README.
So, my „workaround“ is the best I can do.
Thanks.
